# Generated by Django 4.1.6 on 2023-02-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='pics')),
                ('name_1', models.CharField(max_length=250)),
                ('desc_1', models.TextField()),
            ],
        ),
    ]
