# Generated by Django 4.1.6 on 2023-02-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
